# Generated by Django 5.1.6 on 2025-03-22 05:49

import collection.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=collection.models.MediaFile.upload_to)),
                ('status', models.PositiveIntegerField(choices=[(0, 'TRACKED'), (1, 'LOST'), (2, 'DUPLICATED')], default=0)),
                ('is_video', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
                ('creation_year', models.PositiveIntegerField(null=True)),
                ('extension', models.CharField(max_length=10)),
                ('file_size', models.PositiveIntegerField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='categories.category')),
            ],
        ),
    ]
