# Generated by Django 5.1.6 on 2025-03-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='creation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
